spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:     
    
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/uaa/user   
       
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG 
